<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Description>Command-line tool that imports PowerPoint (.pptx) presentations into a LiquidVictor repository</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LiquidVictor.Data.Postgres\LiquidVictor.Data.Postgres.csproj" />
		<ProjectReference Include="..\LiquidVictor.Data.YamlFile\LiquidVictor.Data.YamlFile.csproj" />
		<ProjectReference Include="..\LiquidVictor.Input.Powerpoint\LiquidVictor.Input.Powerpoint.csproj" />
		<ProjectReference Include="..\LiquidVictor\LiquidVictor.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Messages.resx">
			<Generator>MSBuild:Compile</Generator>
			<StronglyTypedFileName>$(IntermediateOutputPath)Messages.Designer.cs</StronglyTypedFileName>
			<StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
			<StronglyTypedNamespace>LVImport</StronglyTypedNamespace>
			<StronglyTypedClassName>Messages</StronglyTypedClassName>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="LVImport.Test" />
	</ItemGroup>

</Project>
