version: '3'
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
     - "5432:5432"
  web:
    image: "adminer"
    ports:
     - "8080:8080"
